# Generated by Django 3.0.7 on 2020-09-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(blank=True, choices=[('Sports', 'Sports'), ('7/11', '7/11'), ('Casino', 'Casino'), ('Slot', 'Slot'), ('Fish', 'Fish')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='game_category',
            field=models.CharField(blank=True, choices=[('Sports', 'Sports'), ('7/11', '7/11'), ('Casino', 'Casino'), ('Slot', 'Slot'), ('Fish', 'Fish')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='restriction_category',
            field=models.CharField(blank=True, choices=[('Sports', 'Sports'), ('7/11', '7/11'), ('Casino', 'Casino'), ('Slot', 'Slot'), ('Fish', 'Fish')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='tag1',
            field=models.CharField(blank=True, choices=[('Promo', 'Promo'), ('Void Credit', 'Void Credit'), ('Free Credit', 'Free Credit'), ('Borrow Credit', 'Borrow Credit'), ('Withdrawal', 'Withdrawal'), ('Recommend', 'Recommend'), ('Lock Credit', 'Lock Credit')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='tag2',
            field=models.CharField(blank=True, choices=[('No Bonus Topup', 'No Bonus (Below Minimum Topup Amount)'), ('Rebate Bonus', 'Rebate Bonus'), ('No Bonus', 'No Bonus'), ('Ticket', 'Ticket')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='usage',
            field=models.CharField(blank=True, choices=[('Twice a Day', 'Twice a Day'), ('Monthly', 'Monthly'), ('Thrice a Day', 'Thrice a Day'), ('Daily', 'Daily'), ('Unlimited', 'Unlimited'), ('Yearly', 'Yearly'), ('One Time Only', 'One Time Only'), ('Weekly', 'Weekly')], max_length=200, null=True),
        ),
    ]
