# Generated by Django 3.1.1 on 2021-01-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210126_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='codename',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(blank=True, choices=[('Casino', 'Casino'), ('7/11', '7/11'), ('Fish', 'Fish'), ('Slot', 'Slot'), ('Sports', 'Sports')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='game_category',
            field=models.CharField(blank=True, choices=[('Casino', 'Casino'), ('7/11', '7/11'), ('Fish', 'Fish'), ('Slot', 'Slot'), ('Sports', 'Sports')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='restriction_category',
            field=models.CharField(blank=True, choices=[('Casino', 'Casino'), ('7/11', '7/11'), ('Fish', 'Fish'), ('Slot', 'Slot'), ('Sports', 'Sports')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='tag1',
            field=models.CharField(blank=True, choices=[('Withdrawal', 'Withdrawal'), ('Borrow Credit', 'Borrow Credit'), ('Free Credit', 'Free Credit'), ('Lock Credit', 'Lock Credit'), ('Void Credit', 'Void Credit'), ('Recommend', 'Recommend'), ('Promo', 'Promo')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='tag2',
            field=models.CharField(blank=True, choices=[('No Bonus Topup', 'No Bonus (Below Minimum Topup Amount)'), ('No Bonus', 'No Bonus'), ('Rebate Bonus', 'Rebate Bonus'), ('Ticket', 'Ticket')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='usage',
            field=models.CharField(blank=True, choices=[('Yearly', 'Yearly'), ('One Time Only', 'One Time Only'), ('Daily', 'Daily'), ('Monthly', 'Monthly'), ('Weekly', 'Weekly'), ('Thrice a Day', 'Thrice a Day'), ('Unlimited', 'Unlimited'), ('Twice a Day', 'Twice a Day')], max_length=200, null=True),
        ),
    ]
