# Generated by Django 3.1.1 on 2021-01-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210126_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(blank=True, choices=[('7/11', '7/11'), ('Slot', 'Slot'), ('Casino', 'Casino'), ('Sports', 'Sports'), ('Fish', 'Fish')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='positions',
            name='codename',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='game_category',
            field=models.CharField(blank=True, choices=[('7/11', '7/11'), ('Slot', 'Slot'), ('Casino', 'Casino'), ('Sports', 'Sports'), ('Fish', 'Fish')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='restriction_category',
            field=models.CharField(blank=True, choices=[('7/11', '7/11'), ('Slot', 'Slot'), ('Casino', 'Casino'), ('Sports', 'Sports'), ('Fish', 'Fish')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='tag1',
            field=models.CharField(blank=True, choices=[('Promo', 'Promo'), ('Borrow Credit', 'Borrow Credit'), ('Withdrawal', 'Withdrawal'), ('Void Credit', 'Void Credit'), ('Free Credit', 'Free Credit'), ('Lock Credit', 'Lock Credit'), ('Recommend', 'Recommend')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='tag2',
            field=models.CharField(blank=True, choices=[('No Bonus', 'No Bonus'), ('Ticket', 'Ticket'), ('Rebate Bonus', 'Rebate Bonus'), ('No Bonus Topup', 'No Bonus (Below Minimum Topup Amount)')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='usage',
            field=models.CharField(blank=True, choices=[('Weekly', 'Weekly'), ('One Time Only', 'One Time Only'), ('Daily', 'Daily'), ('Twice a Day', 'Twice a Day'), ('Yearly', 'Yearly'), ('Unlimited', 'Unlimited'), ('Monthly', 'Monthly'), ('Thrice a Day', 'Thrice a Day')], max_length=200, null=True),
        ),
    ]
