# Generated by Django 3.1.1 on 2020-09-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200922_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(blank=True, choices=[('Sports', 'Sports'), ('Slot', 'Slot'), ('7/11', '7/11'), ('Fish', 'Fish'), ('Casino', 'Casino')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='game_category',
            field=models.CharField(blank=True, choices=[('Sports', 'Sports'), ('Slot', 'Slot'), ('7/11', '7/11'), ('Fish', 'Fish'), ('Casino', 'Casino')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='restriction_category',
            field=models.CharField(blank=True, choices=[('Sports', 'Sports'), ('Slot', 'Slot'), ('7/11', '7/11'), ('Fish', 'Fish'), ('Casino', 'Casino')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='tag1',
            field=models.CharField(blank=True, choices=[('Free Credit', 'Free Credit'), ('Void Credit', 'Void Credit'), ('Recommend', 'Recommend'), ('Borrow Credit', 'Borrow Credit'), ('Withdrawal', 'Withdrawal'), ('Promo', 'Promo'), ('Lock Credit', 'Lock Credit')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='tag2',
            field=models.CharField(blank=True, choices=[('No Bonus', 'No Bonus'), ('Ticket', 'Ticket'), ('No Bonus Topup', 'No Bonus (Below Minimum Topup Amount)'), ('Rebate Bonus', 'Rebate Bonus')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='usage',
            field=models.CharField(blank=True, choices=[('Monthly', 'Monthly'), ('Unlimited', 'Unlimited'), ('Weekly', 'Weekly'), ('One Time Only', 'One Time Only'), ('Yearly', 'Yearly'), ('Daily', 'Daily'), ('Twice a Day', 'Twice a Day'), ('Thrice a Day', 'Thrice a Day')], max_length=200, null=True),
        ),
    ]
