# Generated by Django 3.1.1 on 2021-01-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210126_0510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smsgateway',
            old_name='name',
            new_name='deviceId',
        ),
        migrations.AddField(
            model_name='smsgateway',
            name='token',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(blank=True, choices=[('Fish', 'Fish'), ('Casino', 'Casino'), ('Slot', 'Slot'), ('Sports', 'Sports'), ('7/11', '7/11')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='game_category',
            field=models.CharField(blank=True, choices=[('Fish', 'Fish'), ('Casino', 'Casino'), ('Slot', 'Slot'), ('Sports', 'Sports'), ('7/11', '7/11')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='restriction_category',
            field=models.CharField(blank=True, choices=[('Fish', 'Fish'), ('Casino', 'Casino'), ('Slot', 'Slot'), ('Sports', 'Sports'), ('7/11', '7/11')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='tag1',
            field=models.CharField(blank=True, choices=[('Free Credit', 'Free Credit'), ('Promo', 'Promo'), ('Withdrawal', 'Withdrawal'), ('Recommend', 'Recommend'), ('Void Credit', 'Void Credit'), ('Lock Credit', 'Lock Credit'), ('Borrow Credit', 'Borrow Credit')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='tag2',
            field=models.CharField(blank=True, choices=[('Rebate Bonus', 'Rebate Bonus'), ('Ticket', 'Ticket'), ('No Bonus Topup', 'No Bonus (Below Minimum Topup Amount)'), ('No Bonus', 'No Bonus')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='usage',
            field=models.CharField(blank=True, choices=[('Unlimited', 'Unlimited'), ('Yearly', 'Yearly'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Twice a Day', 'Twice a Day'), ('Thrice a Day', 'Thrice a Day'), ('One Time Only', 'One Time Only')], max_length=200, null=True),
        ),
    ]
