# Generated by Django 3.1.1 on 2020-11-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200926_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbank',
            name='account_number',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(blank=True, choices=[('Casino', 'Casino'), ('Sports', 'Sports'), ('7/11', '7/11'), ('Slot', 'Slot'), ('Fish', 'Fish')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='game_category',
            field=models.CharField(blank=True, choices=[('Casino', 'Casino'), ('Sports', 'Sports'), ('7/11', '7/11'), ('Slot', 'Slot'), ('Fish', 'Fish')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='restriction_category',
            field=models.CharField(blank=True, choices=[('Casino', 'Casino'), ('Sports', 'Sports'), ('7/11', '7/11'), ('Slot', 'Slot'), ('Fish', 'Fish')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='tag1',
            field=models.CharField(blank=True, choices=[('Withdrawal', 'Withdrawal'), ('Promo', 'Promo'), ('Recommend', 'Recommend'), ('Lock Credit', 'Lock Credit'), ('Void Credit', 'Void Credit'), ('Free Credit', 'Free Credit'), ('Borrow Credit', 'Borrow Credit')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='tag2',
            field=models.CharField(blank=True, choices=[('No Bonus', 'No Bonus'), ('Ticket', 'Ticket'), ('Rebate Bonus', 'Rebate Bonus'), ('No Bonus Topup', 'No Bonus (Below Minimum Topup Amount)')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='usage',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('One Time Only', 'One Time Only'), ('Twice a Day', 'Twice a Day'), ('Yearly', 'Yearly'), ('Thrice a Day', 'Thrice a Day'), ('Weekly', 'Weekly'), ('Unlimited', 'Unlimited'), ('Monthly', 'Monthly')], max_length=200, null=True),
        ),
    ]
