# Generated by Django 3.1.1 on 2020-11-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201121_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='account_number',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(blank=True, choices=[('Casino', 'Casino'), ('Slot', 'Slot'), ('Fish', 'Fish'), ('7/11', '7/11'), ('Sports', 'Sports')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='game_category',
            field=models.CharField(blank=True, choices=[('Casino', 'Casino'), ('Slot', 'Slot'), ('Fish', 'Fish'), ('7/11', '7/11'), ('Sports', 'Sports')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='restriction_category',
            field=models.CharField(blank=True, choices=[('Casino', 'Casino'), ('Slot', 'Slot'), ('Fish', 'Fish'), ('7/11', '7/11'), ('Sports', 'Sports')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='tag1',
            field=models.CharField(blank=True, choices=[('Lock Credit', 'Lock Credit'), ('Free Credit', 'Free Credit'), ('Void Credit', 'Void Credit'), ('Recommend', 'Recommend'), ('Withdrawal', 'Withdrawal'), ('Borrow Credit', 'Borrow Credit'), ('Promo', 'Promo')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='tag2',
            field=models.CharField(blank=True, choices=[('Rebate Bonus', 'Rebate Bonus'), ('No Bonus Topup', 'No Bonus (Below Minimum Topup Amount)'), ('No Bonus', 'No Bonus'), ('Ticket', 'Ticket')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='usage',
            field=models.CharField(blank=True, choices=[('Weekly', 'Weekly'), ('One Time Only', 'One Time Only'), ('Daily', 'Daily'), ('Unlimited', 'Unlimited'), ('Thrice a Day', 'Thrice a Day'), ('Twice a Day', 'Twice a Day'), ('Yearly', 'Yearly'), ('Monthly', 'Monthly')], max_length=200, null=True),
        ),
    ]
