# Generated by Django 3.1.1 on 2020-11-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201121_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='account_number',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customerbank',
            name='account_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(blank=True, choices=[('Slot', 'Slot'), ('7/11', '7/11'), ('Casino', 'Casino'), ('Sports', 'Sports'), ('Fish', 'Fish')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='game_category',
            field=models.CharField(blank=True, choices=[('Slot', 'Slot'), ('7/11', '7/11'), ('Casino', 'Casino'), ('Sports', 'Sports'), ('Fish', 'Fish')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='restriction_category',
            field=models.CharField(blank=True, choices=[('Slot', 'Slot'), ('7/11', '7/11'), ('Casino', 'Casino'), ('Sports', 'Sports'), ('Fish', 'Fish')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='tag1',
            field=models.CharField(blank=True, choices=[('Void Credit', 'Void Credit'), ('Borrow Credit', 'Borrow Credit'), ('Free Credit', 'Free Credit'), ('Promo', 'Promo'), ('Lock Credit', 'Lock Credit'), ('Recommend', 'Recommend'), ('Withdrawal', 'Withdrawal')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='tag2',
            field=models.CharField(blank=True, choices=[('Ticket', 'Ticket'), ('No Bonus', 'No Bonus'), ('Rebate Bonus', 'Rebate Bonus'), ('No Bonus Topup', 'No Bonus (Below Minimum Topup Amount)')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='usage',
            field=models.CharField(blank=True, choices=[('Thrice a Day', 'Thrice a Day'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('One Time Only', 'One Time Only'), ('Unlimited', 'Unlimited'), ('Daily', 'Daily'), ('Twice a Day', 'Twice a Day'), ('Yearly', 'Yearly')], max_length=200, null=True),
        ),
    ]
