# Generated by Django 3.1.1 on 2021-01-26 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_auto_20210126_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(blank=True, choices=[('Fish', 'Fish'), ('Casino', 'Casino'), ('Sports', 'Sports'), ('Slot', 'Slot'), ('7/11', '7/11')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='game_category',
            field=models.CharField(blank=True, choices=[('Fish', 'Fish'), ('Casino', 'Casino'), ('Sports', 'Sports'), ('Slot', 'Slot'), ('7/11', '7/11')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='restriction_category',
            field=models.CharField(blank=True, choices=[('Fish', 'Fish'), ('Casino', 'Casino'), ('Sports', 'Sports'), ('Slot', 'Slot'), ('7/11', '7/11')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='tag1',
            field=models.CharField(blank=True, choices=[('Recommend', 'Recommend'), ('Promo', 'Promo'), ('Withdrawal', 'Withdrawal'), ('Void Credit', 'Void Credit'), ('Lock Credit', 'Lock Credit'), ('Borrow Credit', 'Borrow Credit'), ('Free Credit', 'Free Credit')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='tag2',
            field=models.CharField(blank=True, choices=[('Ticket', 'Ticket'), ('No Bonus Topup', 'No Bonus (Below Minimum Topup Amount)'), ('No Bonus', 'No Bonus'), ('Rebate Bonus', 'Rebate Bonus')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='usage',
            field=models.CharField(blank=True, choices=[('Thrice a Day', 'Thrice a Day'), ('Yearly', 'Yearly'), ('One Time Only', 'One Time Only'), ('Twice a Day', 'Twice a Day'), ('Weekly', 'Weekly'), ('Unlimited', 'Unlimited'), ('Monthly', 'Monthly'), ('Daily', 'Daily')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='ActionLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=254)),
                ('description', models.CharField(max_length=254)),
                ('remark', models.CharField(max_length=254)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('remote_id', models.CharField(max_length=254)),
                ('device', models.CharField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
