# Generated by Django 3.1.1 on 2021-01-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201121_0650'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSGateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(blank=True, choices=[('7/11', '7/11'), ('Casino', 'Casino'), ('Slot', 'Slot'), ('Sports', 'Sports'), ('Fish', 'Fish')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='game_category',
            field=models.CharField(blank=True, choices=[('7/11', '7/11'), ('Casino', 'Casino'), ('Slot', 'Slot'), ('Sports', 'Sports'), ('Fish', 'Fish')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='restriction_category',
            field=models.CharField(blank=True, choices=[('7/11', '7/11'), ('Casino', 'Casino'), ('Slot', 'Slot'), ('Sports', 'Sports'), ('Fish', 'Fish')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='tag1',
            field=models.CharField(blank=True, choices=[('Recommend', 'Recommend'), ('Lock Credit', 'Lock Credit'), ('Withdrawal', 'Withdrawal'), ('Void Credit', 'Void Credit'), ('Free Credit', 'Free Credit'), ('Promo', 'Promo'), ('Borrow Credit', 'Borrow Credit')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='tag2',
            field=models.CharField(blank=True, choices=[('Ticket', 'Ticket'), ('Rebate Bonus', 'Rebate Bonus'), ('No Bonus', 'No Bonus'), ('No Bonus Topup', 'No Bonus (Below Minimum Topup Amount)')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='usage',
            field=models.CharField(blank=True, choices=[('Yearly', 'Yearly'), ('Daily', 'Daily'), ('Twice a Day', 'Twice a Day'), ('One Time Only', 'One Time Only'), ('Monthly', 'Monthly'), ('Unlimited', 'Unlimited'), ('Weekly', 'Weekly'), ('Thrice a Day', 'Thrice a Day')], max_length=200, null=True),
        ),
    ]
