# Generated by Django 3.1.1 on 2021-01-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210127_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(blank=True, choices=[('Casino', 'Casino'), ('7/11', '7/11'), ('Slot', 'Slot'), ('Sports', 'Sports'), ('Fish', 'Fish')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='game_category',
            field=models.CharField(blank=True, choices=[('Casino', 'Casino'), ('7/11', '7/11'), ('Slot', 'Slot'), ('Sports', 'Sports'), ('Fish', 'Fish')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='restriction_category',
            field=models.CharField(blank=True, choices=[('Casino', 'Casino'), ('7/11', '7/11'), ('Slot', 'Slot'), ('Sports', 'Sports'), ('Fish', 'Fish')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='tag1',
            field=models.CharField(blank=True, choices=[('Promo', 'Promo'), ('Recommend', 'Recommend'), ('Free Credit', 'Free Credit'), ('Withdrawal', 'Withdrawal'), ('Lock Credit', 'Lock Credit'), ('Borrow Credit', 'Borrow Credit'), ('Void Credit', 'Void Credit')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='tag2',
            field=models.CharField(blank=True, choices=[('Ticket', 'Ticket'), ('Rebate Bonus', 'Rebate Bonus'), ('No Bonus', 'No Bonus'), ('No Bonus Topup', 'No Bonus (Below Minimum Topup Amount)')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='usage',
            field=models.CharField(blank=True, choices=[('Weekly', 'Weekly'), ('One Time Only', 'One Time Only'), ('Unlimited', 'Unlimited'), ('Thrice a Day', 'Thrice a Day'), ('Daily', 'Daily'), ('Twice a Day', 'Twice a Day'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=200, null=True),
        ),
    ]
