# Generated by Django 3.1.1 on 2021-01-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210127_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(blank=True, choices=[('7/11', '7/11'), ('Slot', 'Slot'), ('Fish', 'Fish'), ('Casino', 'Casino'), ('Sports', 'Sports')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='game_category',
            field=models.CharField(blank=True, choices=[('7/11', '7/11'), ('Slot', 'Slot'), ('Fish', 'Fish'), ('Casino', 'Casino'), ('Sports', 'Sports')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='restriction_category',
            field=models.CharField(blank=True, choices=[('7/11', '7/11'), ('Slot', 'Slot'), ('Fish', 'Fish'), ('Casino', 'Casino'), ('Sports', 'Sports')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='tag1',
            field=models.CharField(blank=True, choices=[('Lock Credit', 'Lock Credit'), ('Promo', 'Promo'), ('Recommend', 'Recommend'), ('Void Credit', 'Void Credit'), ('Borrow Credit', 'Borrow Credit'), ('Withdrawal', 'Withdrawal'), ('Free Credit', 'Free Credit')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='tag2',
            field=models.CharField(blank=True, choices=[('No Bonus Topup', 'No Bonus (Below Minimum Topup Amount)'), ('Ticket', 'Ticket'), ('No Bonus', 'No Bonus'), ('Rebate Bonus', 'Rebate Bonus')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='usage',
            field=models.CharField(blank=True, choices=[('One Time Only', 'One Time Only'), ('Thrice a Day', 'Thrice a Day'), ('Twice a Day', 'Twice a Day'), ('Weekly', 'Weekly'), ('Yearly', 'Yearly'), ('Unlimited', 'Unlimited'), ('Daily', 'Daily'), ('Monthly', 'Monthly')], max_length=200, null=True),
        ),
    ]
